# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pytube
        pip install auto-py-to-exe
        pip install -r requeriments.txt
    - name: Lint com flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Teste com unittest
      run: |
        python -m unittest
    - name: Gerar executavel linux
      run: |
        bash config/build.sh
    - name: Salvar executável como artefato
      uses: actions/upload-artifact@v4
      with:
        name: 'Audio youtube download'
        path: 'dist/Audio youtube download'
        compression-level: 0